// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Kl0H4mX57br7SZRA6W7VhT7CKMo-iaw',
    appId: '1:968414890893:web:173a26f18a71b59b090bc4',
    messagingSenderId: '968414890893',
    projectId: 'codex-fashion',
    authDomain: 'codex-fashion.firebaseapp.com',
    storageBucket: 'codex-fashion.firebasestorage.app',
    measurementId: 'G-L90B2KFB1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3sKtmx4poXldGuBvX32kprtAwavMO5Rc',
    appId: '1:968414890893:android:b55467d4f8bd2483090bc4',
    messagingSenderId: '968414890893',
    projectId: 'codex-fashion',
    storageBucket: 'codex-fashion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzu4H1BHyiWfAJIWBxf8Xk1qvLhz1IQTc',
    appId: '1:968414890893:ios:d3fe760c35e22118090bc4',
    messagingSenderId: '968414890893',
    projectId: 'codex-fashion',
    storageBucket: 'codex-fashion.firebasestorage.app',
    iosBundleId: 'com.example.costx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzu4H1BHyiWfAJIWBxf8Xk1qvLhz1IQTc',
    appId: '1:968414890893:ios:d3fe760c35e22118090bc4',
    messagingSenderId: '968414890893',
    projectId: 'codex-fashion',
    storageBucket: 'codex-fashion.firebasestorage.app',
    iosBundleId: 'com.example.costx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0Kl0H4mX57br7SZRA6W7VhT7CKMo-iaw',
    appId: '1:968414890893:web:3872bb256e225615090bc4',
    messagingSenderId: '968414890893',
    projectId: 'codex-fashion',
    authDomain: 'codex-fashion.firebaseapp.com',
    storageBucket: 'codex-fashion.firebasestorage.app',
    measurementId: 'G-EWYV827JHL',
  );
}
